name: Continuous Integration
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    container:
      image: mroynard/latex-maker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build latex
        run: make
      - uses: actions/upload-artifact@master
        with:
          name: cv-artifacts
          path: |
            roynard.cv/*.pdf
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build-latex
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - uses: actions/download-artifact@master
        with:
          name: cv-artifacts
          path: .
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main
